-- MySQL Script generated by MySQL Workbench
-- Sat Jun  8 23:01:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 4whelss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 4whelss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `4whelss` DEFAULT CHARACTER SET utf8 ;
USE `4whelss` ;

-- -----------------------------------------------------
-- Table `4whelss`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4whelss`.`users` (
    `email` VARCHAR(150) NOT NULL,
    `user_name` VARCHAR(150) NOT NULL,
    `pass` VARCHAR(24) NOT NULL,
    `contato` INT(11) NOT NULL,
    PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4whelss`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4whelss`.`marcas` (
    `id_marcas` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(80) NOT NULL,
    PRIMARY KEY (`id_marcas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4whelss`.`carros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4whelss`.`carros` (
    `chassi` INT NOT NULL,
    `modelo` VARCHAR(50) NOT NULL,
    `valor_aluguel` INT NOT NULL,
    `quilometros_rodados` FLOAT NOT NULL,
    `id_marcas` INT NOT NULL,
    PRIMARY KEY (`chassi`),
    INDEX `fk_carros_marcas_idx` (`id_marcas` ASC) VISIBLE,
    CONSTRAINT `fk_carros_marcas`
        FOREIGN KEY (`id_marcas`)
        REFERENCES `4whelss`.`marcas` (`id_marcas`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4whelss`.`alugueis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `4whelss`.`alugueis` (
    `id_aluguel` INT NOT NULL AUTO_INCREMENT,
    `users_email` VARCHAR(150) NOT NULL,
    `contato_usuario` INT(10) NOT NULL,
    `carros_id_carros` INT NOT NULL,
    `data_aluguel` DATE NOT NULL,
    `prazo_aluguel` DATE NOT NULL,
    PRIMARY KEY (`id_aluguel`),
    INDEX `fk_alugueis_users1_idx` (`users_email` ASC) VISIBLE,
    INDEX `fk_alugueis_carros1_idx` (`carros_id_carros` ASC) VISIBLE,
    CONSTRAINT `fk_alugueis_users1`
        FOREIGN KEY (`users_email`)
        REFERENCES `4whelss`.`users` (`email`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT `fk_alugueis_carros1`
        FOREIGN KEY (`carros_id_carros`)
        REFERENCES `4whelss`.`carros` (`chassi`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
